### ISSUE TITLE
fails to build with typescript 1.8.2

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/app-html#1]
typescript at some version after 1.6.2 added checks to the compiler that complain about bad style in the code and refuse to build:

```
Calling TypeScript compiler...
js/util/RestClient.ts(102,51): error TS1313: The body of an 'if'
statement cannot be the empty statement.
js/util/RestClient.ts(146,51): error TS1313: The body of an 'if'
statement cannot be the empty statement.
```

As a workaround, the Dockerfile could be changed to
`RUN npm install -g typescript@1.6.2`, but it would be way better to solve the problem by looking at the few code blocks in the form of

```
if (foo) {
// empty
} else {
handle error
}
```

and changing them to something good-looking.

**Comment by sedrubal** [comment]
As there is now an error using `typescript@1.6.2` I tried to fix it with 9940fba . No idea if this is correct. We're currently testing it in production :angel:
